version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  kafka:
    image: wurstmeister/kafka
    container_name: "kafka-container"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  auth-default:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb
      - kafka
      - zookeeper